<section class="section section--first section--bg section-mobile-view" data-bg="img/section/section.jpg" style="background: url(&quot;img/section/section.jpg&quot;) center center / cover no-repeat;">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="section__wrap">
                    <!-- section title -->
                    <h2 class="section__title">Privacy Policy</h2>
                    <!-- end section title -->

                    <!-- breadcrumb -->
                    <ul class="breadcrumb">
                        <li class="breadcrumb__item"><a href="index.php">Home</a></li>
                        <li class="breadcrumb__item breadcrumb__item--active">Privacy Policy</li>
                    </ul>
                    <!-- end breadcrumb -->
                </div>
            </div>
        </div>
    </div>
</section>

<section class="section section__text">
    <div class="container">
        <div style="padding:20px">
            <p><span style="font-weight: 400;">Privacy Policy</span></p>
            <p>&nbsp;</p>
            <p><span style="font-weight: 400;">Welcome to the web site or mobile application “ShufflesTV.com” website(s) and app (collectively, the "Platform and or Services") of Campout Nigeria Limited (including its subsidiaries, affiliates, agents, and service providers). This Platform is operated by Campout Nigeria Limited and has been created and designed to permit users to submit a video or have their videos uploaded to its affiliate websites (to the Platform, the "Services") for users and visitors ("you," and/or "your") for the purpose of online entertainment. Except as provided below, this Privacy Policy describes and governs how we collect, use, share and protect data collected from users of or visitors to the Platform.</span></p>
            <p><span style="font-weight: 400;">Before you use or submit any information through or in connection with the “Platform and or Services”, please carefully review this Privacy Policy. By using any part of the Services, you consent to the collection, use, and disclosure of your information as further outlined in this Privacy Policy.</span></p>
            <p><br><br></p>
            <p><strong>Information We Collect</strong></p>
            <p><span style="font-weight: 400;">As described below, when you use or otherwise access the Services, we may collect information in multiple ways, including when you provide information directly to us, and when we passively collect information from your browser or device.</span></p>
            <p><strong>Information That You Provide Directly to Us:</strong><span style="font-weight: 400;"> We collect information from you (including, but not limited to, your name, email address, and phone number etc) when you voluntarily provide such information, such as when you download and register to use the ShufflesTV.com app, contact us with inquiries, respond to one of our surveys, provide us with feedback, register for access to the Services, or use certain Services. You may also provide us with information relating to third parties—including information stored in your email and mobile device address books—such as, without limitation, names, email addresses, and phone numbers of your contacts (collectively, “Third-Party Data”). The Services may request your permission to access such Third-Party Data. While you are under no obligation to directly provide us with such information, should you choose to withhold such information, we may not be able to provide you with some or all of the Services. If you provide “personal data” you acknowledge and agree that such personal data may be transferred from your current location to the offices and servers of “ShufflesTV.com” and the authorized third parties. Our Services may include online chats and message boards. Please remember that any information that is disclosed in these areas becomes public information for both us and other users to use and share. Please be considerate and respectful of others while using the community to share your opinions. We reserve the right, but do not have the obligation, to review and monitor such posting or any other content on our Services, and to remove postings or content that may be viewed as inappropriate or offensive to others.</span></p>
            <p><br><br></p>
            <p><strong>Information That is Passively or Automatically Collected</strong></p>
            <p>&nbsp;</p>
            <p><strong>Device &amp; Usage Information:</strong><span style="font-weight: 400;"> When you interact with “ShufflesTV.com” through the Services, we automatically receive and store certain information from devices that you use to access the Services. This information is collected passively using various technologies, and includes the type of internet browser or mobile device you use, any website from which you have come to the Services, your operating system, and may include location data through an IP address that identifies the city and state where you logged into the Platform or your precise geo-location if you have permitted your mobile device to provide that information to us. “ShufflesTV.com” may store such information itself or such information may be included in databases owned and maintained by “ShufflesTV.com” affiliates, agents or service providers. </span></p>
            <p>&nbsp;</p>
            <p><strong>Aggregated Data:</strong><span style="font-weight: 400;"> In an ongoing effort to better understand and serve the users of the Services, “ShufflesTV.com” often conducts research on its customer demographics, interests and behavior based on information we collect. We may de-identify and/or aggregate the information collected through the Services for research purposes or any other purposes, and we may share this data with our affiliates, agents, business partners, or other third parties. </span></p>
            <p>&nbsp;</p>
            <p><strong>Location Information:</strong><span style="font-weight: 400;"> When you access the Services, the Services may request that you provide your city or town, state or country of residence.&nbsp;</span></p>
            <p>&nbsp;</p>
            <p><strong>Cookies and Other Electronic Technologies:</strong><span style="font-weight: 400;"> When you interact with the Services, we try to make that experience simple and meaningful. When you visit our Platform, our web server sends a cookie to your computer or mobile device. Cookies are small pieces of information that are issued to your computer or mobile device when you visit a website or access or use a mobile application, and that store and sometimes track information about your use of the Platform. A number of cookies we use last only for the duration of your web or application session and expire when you close your browser or exit the application. Other cookies are used to remember you when you return to the Platform and will last longer. Some of the cookies used by the Platform are set by us, and some are set by third parties who are delivering services on our behalf. We may use cookies, and similar technologies to cookies, to collect information about your access and use of the Platform. For example, we may use cookies or other technologies that: (1) allow you to navigate and use all the features provided by our Platform; (2) customize elements of the layout and/or content within the Platform and remember that you have visited us before; (3) identify the number of unique visitors we receive; (4) allow us to provide you with a customized experience; and (5) inform us how you use the Platform (including how long you spend on the Platform) and where you have come to the Platform from, so that we can improve the Platform and learn which functions of the Platform are most popular with users. As we adopt additional technologies, we may also gather additional information through other methods. Most web and mobile device browsers automatically accept cookies but, if you prefer, you can change your browser to prevent that or to notify you each time a cookie is set. You can also learn more about cookies by visiting </span><a href="http://www.allaboutcookies.org"><strong>www.allaboutcookies.org</strong></a><span style="font-weight: 400;">, which includes additional useful information on cookies and how to block cookies using different types of browsers or mobile devices. You may also consult the "Help" section of your browser for more information (e.g., </span><a href="http://windows.microsoft.com/en-US/windows-vista/Block-or-allow-cookies"><strong>Internet Explorer</strong></a><span style="font-weight: 400;">; </span><a href="https://support.google.com/chrome/answer/95647"><strong>Google Chrome</strong></a><span style="font-weight: 400;">; </span><a href="http://kb.mozillazine.org/Cookies#Firefox"><strong>Mozilla Firefox</strong></a><span style="font-weight: 400;">; or </span><a href="http://support.apple.com/kb/PH5042"><strong>Apple Safari</strong></a><span style="font-weight: 400;">).&nbsp;</span></p>
            <p><span style="font-weight: 400;">Please note that by blocking any or all cookies, you may not have access to certain features or offerings of the Services.  You can also limit information collection by uninstalling the App on your device and you can use the standard uninstall process available as part of your device for this purpose. </span></p>
            <p><br><br></p>
            <p><strong>Information From Social Networking Services</strong><span style="font-weight: 400;"> One of the special features of the Services is that it may allow you to enable or log into the Services via various social networking services like Facebook, Instagram or Twitter ("Social Networking Service(s)"). By directly integrating these services, we aim to make your online experiences richer and more personalized. To take advantage of this feature, we may ask you to provide your credentials for the applicable Social Networking Service in order to log-in to our Services. When you add a Social Networking Services account to the Services or log into the Services using your Social Networking Services account, we will collect relevant information necessary to enable the Services to access that Social Networking Service and your data contained within that Social Networking Service. As part of such integration, the Social Networking Service will provide us with access to certain information (including, for example, your name and photograph, as well as other information that you permit the Social Network Service to share with us) that you have provided to the Social Networking Service, and we will use, store, and disclose such information in accordance with this Privacy Policy. However, please remember that the manner in which Social Networking Services use, store, and disclose your information is governed by the policies of such third parties, and “ShufflesTV.com” shall have no liability or responsibility for the privacy practices or other actions of any Social Networking Services that may be enabled within the Services. You may also have the option of posting your Services activities to Social Networking Services when you access content through the Services (for example, you may post to Facebook that you performed an activity on the Platform); you acknowledge that if you choose to use this feature, your friends, followers, and subscribers on any Social Networking Services you have enabled will be able to view such activity. Please visit the privacy policy of the relevant Social Networking Service to find out more information about your rights and choices.</span></p>
            <p>&nbsp;</p>
            <p><strong>Our Use of Information Collected</strong></p>
            <p><span style="font-weight: 400;">“ShufflesTV.com” uses the information collected from the Services in a manner that is consistent with this Privacy Policy. If you submit a video, or we upload your video, we may reach out to you to provide helpful tips or advice in connection with your submission. If you provide information for a certain reason, we may use the information in connection with the reason for which it was provided. For instance, if you contact us by email, we will use the information you provide to answer your question or resolve your problem. “ShufflesTV.com” may also use the information we collect through the Services to help us in providing the Services and support services, fulfilling requests for information, receiving and sending communications, updating marketing lists, analyzing data and research aimed at improving the accuracy, effectiveness, usability or popularity of the Services, to personalize the content and advertising that you see on Services and to understand how users interact with and use our advertisement and Services, to associate your activities, customize content or tailor advertising across different device and browsers that you use to access the Services (for instance, computers, tablets, mobile devices, applications and websites), to comply with state, local, federal or international laws, to enforce our </span><a href="https://www.gofundme.com/terms"><strong>Terms of Service</strong></a><span style="font-weight: 400;"> and this Privacy Policy, as otherwise described in this Privacy Policy, or in assisting with other tasks from time to time. Please note that we may combine information that we collect from you and about you (including automatically-collected information) with information we obtain about you from our affiliates and/or non-affiliated third parties, and use such combined information in accordance with this Privacy Policy. We may use your information in the above ways as this is necessary: (i) for our legitimate interest to maintain our relationship with you or protect you and us against fraud; or (ii) to comply with legal obligations.</span></p>
            <p><span style="font-weight: 400;">&nbsp;“ShufflesTV.com” may use the information collected through the Services to contact you about services we believe will be of interest to you.&nbsp;</span></p>
            <p><span style="font-weight: 400;">We may also use data collected through the Services to send communications relating to the Services.For example, we may send periodic emails to registered users of the Services relating to their recent interactions with the Services. In addition to sending the foregoing communications, we may also send reminders or related messages to you and to third parties from time to time.&nbsp;</span></p>
            <p><strong>Mobile Services:</strong><span style="font-weight: 400;"> If you access the Services through a mobile device, you agree that we may communicate with you regarding “ShufflesTV.com” by SMS, MMS, text message, or other electronic means to your mobile device. In the event you change or deactivate your mobile telephone number, you agree to promptly update your “ShufflesTV.com” account information to ensure that your messages are not misdirected. Please note that your wireless service carrier’s standard charges, data rates, and other fees may apply where you access the Services through a mobile device. In addition, downloading, installing, or using certain Services on a mobile device may be prohibited or restricted by your carrier, and not all Services may work with all carriers or devices.</span></p>
            <p>&nbsp;</p>
            <p><strong>Our Disclosure of Information Collected Through the Services</strong></p>
            <p><span style="font-weight: 400;">There are certain circumstances in which we may share information collected through the Services with certain third parties without further notice to you, as set forth below:</span></p>
            <p><strong>Business Transfers:</strong><span style="font-weight: 400;"> As we develop our business, we might sell or buy businesses or assets. In the event of a corporate sale, merger, reorganization, dissolution, similar event, or steps taken in anticipation of such events (e.g., due diligence in a transaction), user information may be part of the transferred assets. </span></p>
            <p><strong>Agents, Consultants, Vendors and Related Third Parties:</strong></p>
            <p><span style="font-weight: 400;">“ShufflesTV.com”, like many businesses, sometimes hires other companies to perform certain business-related functions on its behalf, and we may provide access to or share your information with these companies so they can perform services for us. Examples of such functions include marketing, mailing information, data storage, security, fraud preventions, payment processing, legal services, and maintaining databases.&nbsp;</span></p>
            <p><strong>Legal Requirements:</strong><span style="font-weight: 400;"> ” ShufflesTV.com” may access, disclose, transfer and preserve your information when we have a good faith belief that doing so is necessary to: (i) comply with the law, search warrants, court orders, and another legal process; and respond to inquiries or requests from government, regulatory, law enforcement, public authorities, or content protection organizations; (ii) protect and defend the legal rights, privacy, safety or property of “ShufflesTV.com”, its affiliates, subsidiaries, employees, agents, contractors, or its users; (iii) permit us to pursue available remedies, commence, participate in, or defend litigation, or limit the damages we may sustain; or (iv) enforce this Privacy Policy or any applicable Terms of Service. </span></p>
            <p><strong>Video Submitters</strong><span style="font-weight: 400;"> If you submit a video, or your video is uploaded to “ShufflesTV.com” Platform and or Services, any user on the site may be able to contact you. In all such instances, you are fully responsible for any and all shared information or contact, online and offline, with any user on the Platform and the sharing of your information is at your own risk.&nbsp;</span></p>
            <p><strong>Aggregate and/or De-Identified Information</strong><span style="font-weight: 400;"> We may aggregate and/or de-identify your information so that the information no longer relates to you individually. Our use and disclosures of such aggregated or de-identified information is not subject to this Privacy Policy, and may be disclosed to others without limitation and for any purpose. </span></p>
            <p><strong>Analytics</strong><span style="font-weight: 400;"> We may use third-party web analytics services on our Services, such as those of Google Analytics. These service providers use the sort of technology previously described in the “Cookies and other electronic technologies” section to help us analyze how users use the Services, including by noting the third-party website from which you arrive, and provide certain features to you. The information (including your IP address) collected by the technology will be disclosed to or collected directly by these service providers, who use the information to evaluate your use of the Services. This information may be used to place interest-based advertisements on the Platform. This may result in you seeing advertisements for our Platform when you visit other websites.&nbsp;</span></p>
            <p>&nbsp;</p>
            <p><strong>Tailored Advertising</strong></p>
            <p><span style="font-weight: 400;">We may use third-party advertising technologies that allow for the delivery of relevant content and advertising on our Platform, as well as on other websites you visit. The ads may be based on various factors such as the content of the page you are visiting, information you enter such as your age and gender, your searches, demographic data, user-generated content, and other information we collect from you. These ads may be based on your current activity or your activity over time and across other websites and online services and may be tailored to your interests.</span></p>
            <p><span style="font-weight: 400;">Also, third parties whose products or services are accessible or advertised on our Platform may place cookies or other tracking technologies on your computer, mobile phone, or other device to collect information about your use of the website as discussed above. We also allow other third parties (e.g., ad networks and ad servers such as Google Analytics, DoubleClick and others) to serve tailored ads to you on our website, other sites, and in other applications, and to access their own cookies or other tracking technologies on your computer, mobile phone, or other device you use to access the website. We may provide our customer information (such as a hashed version of your email addresses) to service providers, who may “match” this information in de-identified form to cookies (or mobile ad identifiers) and other proprietary IDs, in order to target or “retarget” you with ads when you visit other websites and mobile applications.&nbsp;</span></p>
            <p><span style="font-weight: 400;">We neither have access to, nor does this Privacy Policy govern, the use of cookies or other tracking technologies that may be placed on your computer, mobile phone, or other devices you use to access our website by non-affiliated, third-party ad technology, ad servers, ad networks or any other non-affiliated third parties.&nbsp;</span></p>
            <p><span style="font-weight: 400;">To opt out of Google Analytics for display advertising or customize Google display network ads, you can visit the </span><a href="https://adssettings.google.com/authenticated"><strong>Google Ads Settings page</strong></a><span style="font-weight: 400;">.</span></p>
            <p><span style="font-weight: 400;">Please note that to the extent advertising technology is integrated into our website or other websites that you visit, you may still receive advertisements even if you opt-out. In that case, the advertising will not be tailored to your interests. Also, we do not control any of the above opt-out links or whether any particular company chooses to participate in these opt-out programs. We are not responsible for any choices you make using these mechanisms or the continued availability or accuracy of these mechanisms.</span></p>
            <p><strong>Unsolicited Information</strong></p>
            <p><span style="font-weight: 400;">Please be advised that some information you provide may be publicly accessible, such as information posted in forums or comment sections. We may also collect information through customer support communications, your communication to us of ideas for new products or modifications to existing products, and other unsolicited submissions (collectively, with publicly-accessible information, "Unsolicited Information"). By sending us Unsolicited Information, you further (a) agree that we are under no obligation of confidentiality, express or implied, with respect to the Unsolicited Information, (b) acknowledge that we may have something similar to the Unsolicited Information already under consideration or in development, (c) grant us an irrevocable, non-exclusive, royalty-free, perpetual, worldwide license to use, modify, prepare derivative works, publish, distribute and sublicense the Unsolicited Information, (d) irrevocably waive, and cause to be waived, against “ShufflesTV.com” and its users any claims and assertions of any moral rights contained in such Unsolicited Information and (e) fully aware of the risks of disclosing such unsolicited or following the contents or engaging in contact with the poster of such unsolicited information and hold “ShufflesTV.com” non liable for any further contact, physical or online, outside of your use of the Services on the Platform. This Unsolicited Information section shall survive any termination of your account or the Services. This Privacy Policy otherwise does not apply to any information collected by “ShufflesTV.com” other than information collected through the Services.</span></p>
            <p>&nbsp;</p>
            <p><strong>Children</strong></p>
            <p><span style="font-weight: 400;">Our Services are not designed for use by individuals under the age of 18. If you have reason to believe that a child under the age of 18 has provided personal information to “ShufflesTV.com” through the Services, without parental or legal guardian permission or consent, please contact us </span><a href="mailto:support@CampOut9ja.com"><strong>support@ShufflesTV.com.com</strong></a><span style="font-weight: 400;">, and we will delete that information from our databases to the extent required by law.</span></p>
            <p>&nbsp;</p>
            <p><strong>Links to Other Web Sites</strong></p>
            <p><span style="font-weight: 400;">This Privacy Policy applies only to the “Services” provided by “ShufflesTV.com”. The Services may contain links to other web sites not operated or controlled by “ShufflesTV.com” (the "Third-Party Sites"). The policies and procedures we described here do not apply to the Third-Party Sites. The links from the Services do not imply that “ShufflesTV.com” endorses or has reviewed the Third-Party Sites. We suggest contacting those sites directly for information on their respective privacy policies.</span></p>
            <p>&nbsp;</p>
            <p><strong>Security</strong></p>
            <p><span style="font-weight: 400;">“ShufflesTV.com” has implemented technical and organizational security measures to protect the Personal Data provided via the Services from loss, misuse, and unauthorized access, disclosure, alteration, or destruction. For example, limiting access to information only to employees and authorized service providers who need to know such information.&nbsp;</span></p>
            <p><span style="font-weight: 400;">However, no Internet or email transmission is ever fully secure or error-free. In particular, email sent to or from the Services may not be secure. Therefore, you should take special care in deciding what information you send to us via email. Please keep this in mind when disclosing any information to “ShufflesTV.com” via the Internet. In all or any cases where or if there is a breach of your information, you accept full risk &amp; responsibility for sharing that information. Only send information for your use of the Platform or Services for which you believe can be public without any harm to you.</span></p>
            <p>&nbsp;</p>
            <p><strong>Retention of your information</strong></p>
            <p><span style="font-weight: 400;">We will only retain the information for as long as necessary for the purpose for which that information was collected.&nbsp;</span></p>
            <p>&nbsp;</p>
            <p><strong>Changes to “ShufflesTV.com”s Privacy Policy</strong></p>
            <p><span style="font-weight: 400;">Services and our business may change from time to time. As a result, at times it may be necessary for “ShufflesTV.com” to make changes to this Privacy Policy. “ShufflesTV.com” reserves the right to update or modify this Privacy Policy at any time and from time to time. If you disagree with our revisions to the Privacy Policy, you may de-activate your account or discontinue the use of our Services. Please review this policy periodically, and especially before you provide us with any information through the Services. This Privacy Policy was last updated on the date indicated below. Your continued use of the Services after any changes or revisions to this Privacy Policy shall indicate your agreement with the terms of such revised Privacy Policy.</span></p>
            <p><br><br></p>
            <p><span style="font-weight: 400;">June 2019</span></p>
        </div>
<br />
<br />
    </div>
</section>